# Generated by Django 5.2.1 on 2025-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Менеджер', max_length=50)),
                ('deals_in_progress', models.PositiveIntegerField(default=0)),
                ('current_month_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
